##
# Ansible playbook for setting up your Ubuntu (terminal only) Environment
#
---
- hosts: local
  become: false

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: create /bin/src/tmp dir
      file: path="{{ item }}" state=directory mode=0755
      with_items:
        - ~/bin
        - ~/src
        - ~/pkg
        - ~/tmp
  tasks:
    - import_tasks: tasks/misc-packages.yml
      tags: ['misc']

  roles:
    - role: geerlingguy.dotfiles             # Must be first
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: aussielunix.rbenv
      when: rbenv
      tags: ['rbenv', 'ruby']
