---
roles:
  - name: geerlingguy.dotfiles
  - name: aussielunix.rbenv
  - name: robertdebock.hashicorp

collections: []

# collections:
#  - name: https://github.com/aussielunix/ansible-collection-mac.git,1.1.3
#    type: git
