---
roles:
  - name: geerlingguy.dotfiles
  - name: aussielunix.rbenv
  - name: aussielunix.hashicorp
  - name: diodonfrost.terragrunt

collections: []

# collections:
#  - name: https://github.com/aussielunix/ansible-collection-mac.git,1.1.3
#    type: git
