#!/usr/bin/env bash

MYSTATION_REPO="git@github.com:aussielunix/ubuntu-dev-playbook.git"

#######################################################################################
cat <<End-of-message
░█▀█░█▀█░▀▀█░█░█░█▀█░█▀█
░█▀▀░█▀█░░░█░█░█░█░█░█▀█
░▀░░░▀░▀░▀▀░░▀▀▀░▀░▀░▀░▀

by Mick Pollard <twitter.com/aussielunix>

End-of-message

if [[ -d ~/.pajuna ]]
then
  echo -e "\e[32mThe folder \".pajuna\" already exists. Aborting.\e[0m"
  exit 1
fi

if ! hash git 2>/dev/null
then
  echo -e "\e[32mInstalling git.......\e[0m"
  sudo -E DEBIAN_FRONTEND=noninteractive apt-get -y install git
fi

if ! hash ansible 2>/dev/null
then
  echo -e "\e[32mAdding the Ansible PPA.......\e[0m"
  sudo -E DEBIAN_FRONTEND=noninteractive apt-get -y install software-properties-common
  sudo apt-add-repository -yu ppa:ansible/ansible
  echo -e "\e[32mInstalling Ansible from PPA.......\e[0m"
  sudo -E DEBIAN_FRONTEND=noninteractive apt-get -y install ansible
fi

# clone pajuna/mystation
echo -e "\e[32mThe folder \".pajuna\" doesn't exist. Creating....\e[0m"
git clone ${MYSTATION_REPO} ~/.pajuna

# echo out welcome message etc
echo
echo -e "\e[36mBootstrap is complete....\e[0m"
echo -e "\e[36mYou should set an alias up for pajuna....\e[0m]"
echo -e "\e[92malias pajuna='ANSIBLE_CONFIG=~/.pajuna/ansible.cfg ansible-playbook -i ~/.pajuna/inventory ~/.pajuna/main.yml' \e[0m"
echo -e "\nNow install the roles from Galaxy - cd ~/.pajuna && ansible-galaxy install -r requirements.yml...\n"
echo -e "\nNow run pajuna -K....\n"

# vim: autoindent tabstop=2 shiftwidth=2 expandtab softtabstop=2 filetype=sh
